package com.cubepro.timetable;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.cubepro.classes.ClassDetails;
import com.cubepro.staff.StaffDetails;
import com.cubepro.subject.SubjectDetails;

/**
 * TimeTableDetails generated by MyEclipse Persistence Tools
 */
public class TimeTableDetails implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -7410152287855719312L;

	private Integer timeTableDetailId = Integer.valueOf(0);

	private ClassDetails classDetails = new ClassDetails();

	private StaffDetails staffDetailsByStaffId = new StaffDetails();

	private StaffDetails staffDetailsByReplacementStaffId;

	private Integer day;

	private String dayValue;

	private Integer year;

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;
	
	private String periods;

	private SubjectDetails subjectDetails = new SubjectDetails();

	// Constructors

	/** default constructor */
	public TimeTableDetails() {
	}

	/** minimal constructor */
	public TimeTableDetails(Integer timeTableDetailId,
			ClassDetails classDetails, StaffDetails staffDetailsByStaffId,
			StaffDetails staffDetailsByReplacementStaffId, Integer day,
			Integer year, Date createDate, Integer createUserId) {
		this.timeTableDetailId = timeTableDetailId;
		this.classDetails = classDetails;
		this.staffDetailsByStaffId = staffDetailsByStaffId;
		this.staffDetailsByReplacementStaffId = staffDetailsByReplacementStaffId;
		this.day = day;
		this.year = year;
		this.createDate = createDate;
		this.createUserId = createUserId;
	}

	/** full constructor */
	public TimeTableDetails(Integer timeTableDetailId,
			ClassDetails classDetails, StaffDetails staffDetailsByStaffId,
			StaffDetails staffDetailsByReplacementStaffId, Integer day,
			Integer year, Date createDate, Integer createUserId,
			Date changeDate, Integer changeUserId) {
		this.timeTableDetailId = timeTableDetailId;
		this.classDetails = classDetails;
		this.staffDetailsByStaffId = staffDetailsByStaffId;
		this.staffDetailsByReplacementStaffId = staffDetailsByReplacementStaffId;
		this.day = day;
		this.year = year;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
	}

	// Property accessors

	public Integer getTimeTableDetailId() {
		return this.timeTableDetailId;
	}

	public void setTimeTableDetailId(Integer timeTableDetailId) {
		this.timeTableDetailId = timeTableDetailId;
	}

	public ClassDetails getClassDetails() {
		return this.classDetails;
	}

	public void setClassDetails(ClassDetails classDetails) {
		this.classDetails = classDetails;
	}

	public StaffDetails getStaffDetailsByStaffId() {
		return this.staffDetailsByStaffId;
	}

	public void setStaffDetailsByStaffId(StaffDetails staffDetailsByStaffId) {
		this.staffDetailsByStaffId = staffDetailsByStaffId;
	}

	public StaffDetails getStaffDetailsByReplacementStaffId() {
		return this.staffDetailsByReplacementStaffId;
	}

	public void setStaffDetailsByReplacementStaffId(
			StaffDetails staffDetailsByReplacementStaffId) {
		this.staffDetailsByReplacementStaffId = staffDetailsByReplacementStaffId;
	}

	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public SubjectDetails getSubjectDetails() {
		return subjectDetails;
	}

	public void setSubjectDetails(SubjectDetails subjectDetails) {
		this.subjectDetails = subjectDetails;
	}

	public String getDayValue() {
		if (dayValue == null || dayValue.trim().length() > 0) {
			if (day.intValue() == 1)
				dayValue = "MONDAY";
			if (day.intValue() == 2)
				dayValue = "TUESDAY";
			if (day.intValue() == 3)
				dayValue = "WEDNESDAY";
			if (day.intValue() == 4)
				dayValue = "THURSDAY";
			if (day.intValue() == 5)
				dayValue = "FRIDAY";
			if (day.intValue() == 6)
				dayValue = "SATURDAY";
			if (day.intValue() == 7)
				dayValue = "SUNDAY";
		}
		return dayValue;
	}

	public void setDayValue(String dayValue) {
		if (dayValue == null || dayValue.trim().length() > 0) {
			if (day.intValue() == 1)
				this.dayValue = "MONDAY";
			if (day.intValue() == 2)
				this.dayValue = "TUESDAY";
			if (day.intValue() == 3)
				this.dayValue = "WEDNESDAY";
			if (day.intValue() == 4)
				this.dayValue = "THURSDAY";
			if (day.intValue() == 5)
				this.dayValue = "FRIDAY";
			if (day.intValue() == 6)
				this.dayValue = "SATURDAY";
			if (day.intValue() == 7)
				this.dayValue = "SUNDAY";
		} else {
			this.dayValue = dayValue;
		}
	}

	public String getPeriods() {
		return periods;
	}

	public void setPeriods(String periods) {
		this.periods = periods;
	}

}
