package com.cubepro.invoice;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import bsh.StringUtil;

import com.cubepro.fees.FeesDetails;
import com.cubepro.student.StudentDetails;
import com.cubepro.util.DateUtils;
import com.cubepro.util.StringUtils;

/**
 * InvoiceDetails generated by MyEclipse Persistence Tools
 */
public class InvoiceDetails implements
		java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -5307128633151455675L;

	private Integer invoiceId = Integer.valueOf(0);

	private StudentDetails studentDetails = new StudentDetails();

	private Integer feesId  = Integer.valueOf(0);

	private String invoiceNo = "";

	private Date invoiceDate;

	private Double totalAmtPaid = Double.valueOf(0);

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;
	
	private String subType;
	
	private String paidBy;
	
	private String payBy;
	
	private String chqNo;
	
	private String fine;
	
	private String conc;
	
	private String studentType;
	
	private String feesType;
	
	private String feesDate;
	
	private String transportFee;
	
	private String hostelFee;

	private String grossAmt;
	
	private String scholarAmt;
	
	private String paidAmt;
	
	private String balanceAmt;
	
	// Constructors

	/** default constructor */
	public InvoiceDetails() {
	}

	/** minimal constructor */
	public InvoiceDetails(Integer invoiceId,
			StudentDetails studentDetails, FeesDetails feesDetails,
			String invoiceNo, Date invoiceDate, Double totalAmtPaid,
			Date createDate, Integer createUserId) {
		this.invoiceId = invoiceId;
		this.studentDetails = studentDetails;
		this.invoiceNo = invoiceNo;
		this.invoiceDate = invoiceDate;
		this.totalAmtPaid = totalAmtPaid;
		this.createDate = createDate;
		this.createUserId = createUserId;
	}

	/** full constructor */
	public InvoiceDetails(Integer invoiceId,
			StudentDetails studentDetails, FeesDetails feesDetails,
			String invoiceNo, Date invoiceDate, Double totalAmtPaid,
			Date createDate, Integer createUserId, Date changeDate,
			Integer changeUserId) {
		this.invoiceId = invoiceId;
		this.studentDetails = studentDetails;
		this.invoiceNo = invoiceNo;
		this.invoiceDate = invoiceDate;
		this.totalAmtPaid = totalAmtPaid;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
	}

	// Property accessors

	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	public StudentDetails getStudentDetails() {
		return this.studentDetails;
	}

	public void setStudentDetails(StudentDetails studentDetails) {
		this.studentDetails = studentDetails;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public Double getTotalAmtPaid() {
		return this.totalAmtPaid;
	}

	public void setTotalAmtPaid(Double totalAmtPaid) {
		this.totalAmtPaid = totalAmtPaid;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public String getSubType() {
		return subType;
	}

	public void setSubType(String subType) {
		this.subType = subType;
	}

	public String getPaidBy() {
		return paidBy;
	}

	public void setPaidBy(String paidBy) {
		this.paidBy = paidBy;
	}

	public String getPayBy() {
		return payBy;
	}

	public void setPayBy(String payBy) {
		this.payBy = payBy;
	}

	public String getChqNo() {
		return chqNo;
	}

	public void setChqNo(String chqNo) {
		this.chqNo = chqNo;
	}

	public String getFine() {
		return fine;
	}

	public void setFine(String fine) {
		this.fine = fine;
	}

	public String getStudentType() {
		return studentType;
	}

	public void setStudentType(String studentType) {
		this.studentType = studentType;
	}

	public String getFeesType() {
		return feesType;
	}

	public void setFeesType(String feesType) {
		this.feesType = feesType;
	}

	public Integer getFeesId() {
		return feesId;
	}

	public void setFeesId(Integer feesId) {
		this.feesId = feesId;
	}

	public String getFeesDate() {
		if(StringUtils.isEmpty(feesDate) == true){
			try{
			feesDate = DateUtils.dateToString(new Date(), "dd/MM/yyyy");
			}catch(Exception e){}
		}
		return feesDate;
	}

	public void setFeesDate(String feesDate) {
		if(StringUtils.isEmpty(feesDate) == true){
			try{
			feesDate = DateUtils.dateToString(new Date(), "dd/MM/yyyy");
			}catch(Exception e){}
		}
		this.feesDate = feesDate;
	}

	public String getConc() {
		return conc;
	}

	public void setConc(String conc) {
		this.conc = conc;
	}

	public String getTransportFee() {
		return transportFee;
	}

	public void setTransportFee(String transportFee) {
		this.transportFee = transportFee;
	}

	public String getHostelFee() {
		return hostelFee;
	}

	public void setHostelFee(String hostelFee) {
		this.hostelFee = hostelFee;
	}

	public String getGrossAmt() {
		return grossAmt;
	}

	public void setGrossAmt(String grossAmt) {
		this.grossAmt = grossAmt;
	}

	public String getScholarAmt() {
		return scholarAmt;
	}

	public void setScholarAmt(String scholarAmt) {
		this.scholarAmt = scholarAmt;
	}

	public String getPaidAmt() {
		return paidAmt;
	}

	public void setPaidAmt(String paidAmt) {
		this.paidAmt = paidAmt;
	}

	public String getBalanceAmt() {
		return balanceAmt;
	}

	public void setBalanceAmt(String balanceAmt) {
		this.balanceAmt = balanceAmt;
	}


}
