package com.cubepro.classes;

// Generated by MyEclipse Persistence Tools

import java.util.HashSet;
import java.util.Set;

/**
 * ClassDetails generated by MyEclipse Persistence Tools
 */
public class ClassDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8386440465897064621L;

	private Integer classId;

	private String className;

	private Integer noOfStudents;

	private String sectionName;

	private String staffInChargeId;
	
	private String classWithSectionName;
	
	private String classNameInWords;

	private String status;
	
	private String classType;
	
	private String classCode;
	
	private String classDetailName;
	
	private Set timeTableDetailses = new HashSet(0);

	private Set examDetailses = new HashSet(0);

	private Set studentDetailses = new HashSet(0);

	private Set markDetailses = new HashSet(0);

	private Set subjectDetailses = new HashSet(0);

	private Set feesDetailses = new HashSet(0);

	private Set staffDetailses = new HashSet(0);

	// Constructors

	/** default constructor */
	public ClassDetails() {
	}

	/** minimal constructor */
	public ClassDetails(Integer classId, String className,
			Integer noOfStudents, String sectionName, String staffInChargeId) {
		this.classId = classId;
		this.className = className;
		this.noOfStudents = noOfStudents;
		this.sectionName = sectionName;
		this.staffInChargeId = staffInChargeId;
	}

	/** full constructor */
	public ClassDetails(Integer classId, String className,
			Integer noOfStudents, String sectionName, Integer staffInChargeId,
			Set timeTableDetailses, Set examDetailses, Set studentDetailses,
			Set markDetailses, Set subjectDetailses, Set feesDetailses,
			Set staffDetailses) {
		this.classId = classId;
		this.className = className;
		this.noOfStudents = noOfStudents;
		this.sectionName = sectionName;
		this.timeTableDetailses = timeTableDetailses;
		this.examDetailses = examDetailses;
		this.studentDetailses = studentDetailses;
		this.markDetailses = markDetailses;
		this.subjectDetailses = subjectDetailses;
		this.feesDetailses = feesDetailses;
		this.staffDetailses = staffDetailses;
	}

	// Property accessors

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Integer getNoOfStudents() {
		return this.noOfStudents;
	}

	public void setNoOfStudents(Integer noOfStudents) {
		this.noOfStudents = noOfStudents;
	}

	public String getSectionName() {
		return this.sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	public String getStaffInChargeId() {
		return this.staffInChargeId;
	}

	public void setStaffInChargeId(String staffInChargeId) {
		this.staffInChargeId = staffInChargeId;
	}

	public Set getTimeTableDetailses() {
		return this.timeTableDetailses;
	}

	public void setTimeTableDetailses(Set timeTableDetailses) {
		this.timeTableDetailses = timeTableDetailses;
	}

	public Set getExamDetailses() {
		return this.examDetailses;
	}

	public void setExamDetailses(Set examDetailses) {
		this.examDetailses = examDetailses;
	}

	public Set getStudentDetailses() {
		return this.studentDetailses;
	}

	public void setStudentDetailses(Set studentDetailses) {
		this.studentDetailses = studentDetailses;
	}

	public Set getMarkDetailses() {
		return this.markDetailses;
	}

	public void setMarkDetailses(Set markDetailses) {
		this.markDetailses = markDetailses;
	}

	public Set getSubjectDetailses() {
		return this.subjectDetailses;
	}

	public void setSubjectDetailses(Set subjectDetailses) {
		this.subjectDetailses = subjectDetailses;
	}

	public Set getFeesDetailses() {
		return this.feesDetailses;
	}

	public void setFeesDetailses(Set feesDetailses) {
		this.feesDetailses = feesDetailses;
	}

	public Set getStaffDetailses() {
		return this.staffDetailses;
	}

	public void setStaffDetailses(Set staffDetailses) {
		this.staffDetailses = staffDetailses;
	}

	public String getClassWithSectionName() {
		return classWithSectionName;
	}

	public void setClassWithSectionName(String classWithSectionName) {
		this.classWithSectionName = classWithSectionName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getClassNameInWords() {
		if(className.equals("X")){
			classNameInWords =  "TENTH";
		}else if(className.equals("XI")){
			classNameInWords ="ELEVENTH";
		}else if(className.equals("XII")){
			classNameInWords ="TWELVETH";
		}else if(className.equals("I")){
			classNameInWords ="FIRST";
		}else if(className.equals("II")){
			classNameInWords ="SECOND";
		}else if(className.equals("III")){
			classNameInWords ="THIRD";
		}else if(className.equals("IV")){
			classNameInWords ="FOURTH";
		}else if(className.equals("V")){
			classNameInWords ="FIFTH";
		}else if(className.equals("VI")){
			classNameInWords ="SIXTH";
		}else if(className.equals("VII")){
			classNameInWords ="SEVENTH";
		}else if(className.equals("VIII")){
			classNameInWords ="EIGHTH";
		}else if(className.equals("IX")){
			classNameInWords ="NINETH";
		}
		return classNameInWords;
	}

	public void setClassNameInWords(String classNameInWords) {
		this.classNameInWords = classNameInWords;
	}

	public String getClassType() {
		return classType;
	}

	public void setClassType(String classType) {
		this.classType = classType;
	}

	public String getClassCode() {
		return classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	public String getClassDetailName() {
		return classDetailName;
	}

	public void setClassDetailName(String classDetailName) {
		this.classDetailName = classDetailName;
	}

}
