package com.cubepro.util;

import java.sql.Blob;


/**
 * FileAttachment generated by MyEclipse - Hibernate Tools
 */

public class FileAttachment  implements java.io.Serializable {

	private static final long serialVersionUID = 4298648465960786193L;

    // Fields    
	private Long fileAttachmentId;
    private String name;
    private Blob object;
    private Integer contentTypeId;
    private Boolean compressed;
    private Long entityId;
    private Integer entityType;
    private Integer sequenceNumber;


    // Constructors

    /** default constructor */
    public FileAttachment() {
    	//For hibernate
    }

    
    /** full constructor */
    public FileAttachment(String name, Blob object, Integer contentTypeId, Boolean compressed, Long entityId, Integer entityType, Integer sequenceNumber) {
        this.name = name;
        this.object = object;
        this.contentTypeId = contentTypeId;
        this.compressed = compressed;
        this.entityId = entityId;
        this.entityType = entityType;
        this.sequenceNumber = sequenceNumber;
    }

   
    // Property accessors

    public Long getFileAttachmentId() {
        return this.fileAttachmentId;
    }
    
    public void setFileAttachmentId(Long fileAttachmentId) {
        this.fileAttachmentId = fileAttachmentId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Blob getObject() {
        return this.object;
    }
    
    public void setObject(Blob object) {
        this.object = object;
    }

    public Integer getContentTypeId() {
        return this.contentTypeId;
    }
    
    public void setContentTypeId(Integer contentTypeId) {
        this.contentTypeId = contentTypeId;
    }

    public Boolean getCompressed() {
        return this.compressed;
    }
    
    public void setCompressed(Boolean compressed) {
        this.compressed = compressed;
    }

    public Long getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public Integer getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }

    public Integer getSequenceNumber() {
        return this.sequenceNumber;
    }
    
    public void setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }
}