package com.cubepro.roll;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Role1 generated by MyEclipse - Hibernate Tools
 */

public class Role  implements java.io.Serializable {

	
}