package com.cubepro.exam;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.cubepro.classes.ClassDetails;

/**
 * ExamDetails generated by MyEclipse Persistence Tools
 */
public class ExamDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1794144783094859512L;

	private Integer examId = Integer.valueOf(0);

	private ClassDetails classDetails = new ClassDetails();

	private String examType;

	private String subjectName;
	
	private Date dateOfExam;

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;
	
	private String status;

	private Set markDetailses = new HashSet(0);

	// Constructors

	/** default constructor */
	public ExamDetails() {
	}

	/** minimal constructor */
	public ExamDetails(Integer examId, ClassDetails classDetails,
			String examType, String subjectName, Date dateOfExam,
			Date createDate, Integer createUserId, Date changeDate,
			Integer changeUserId) {
		this.examId = examId;
		this.classDetails = classDetails;
		this.examType = examType;
		this.subjectName = subjectName;
		this.dateOfExam = dateOfExam;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
	}

	/** full constructor */
	public ExamDetails(Integer examId, ClassDetails classDetails,
			String examType, String subjectName, Date dateOfExam,
			Date createDate, Integer createUserId, Date changeDate,
			Integer changeUserId, Set markDetailses) {
		this.examId = examId;
		this.classDetails = classDetails;
		this.examType = examType;
		this.subjectName = subjectName;
		this.dateOfExam = dateOfExam;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
		this.markDetailses = markDetailses;
	}

	// Property accessors

	public Integer getExamId() {
		return this.examId;
	}

	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	public ClassDetails getClassDetails() {
		return this.classDetails;
	}

	public void setClassDetails(ClassDetails classDetails) {
		this.classDetails = classDetails;
	}

	public String getExamType() {
		return this.examType;
	}

	public void setExamType(String examType) {
		this.examType = examType;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Date getDateOfExam() {
		return this.dateOfExam;
	}

	public void setDateOfExam(Date dateOfExam) {
		this.dateOfExam = dateOfExam;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public Set getMarkDetailses() {
		return this.markDetailses;
	}

	public void setMarkDetailses(Set markDetailses) {
		this.markDetailses = markDetailses;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
