package com.cubepro.login.entity;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.cubepro.login.LoginHelper;

/**
 * LoginDetails generated by MyEclipse Persistence Tools
 */

public class LoginDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -740695789442615691L;


	// Fields

	private Integer userId;

	private String userName;

	private String password;

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;

	private String status;

	// Constructors

	/** default constructor */
	public LoginDetails() {
	}

	/** minimal constructor */
	public LoginDetails(Integer userId, String userName, String password,
			Date createDate, Integer createUserId, String status) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.status = status;
	}

	/** full constructor */
	public LoginDetails(Integer userId, String userName, String password,
			Date createDate, Integer createUserId, Date changeDate,
			Integer changeUserId, String status) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
		this.status = status;
	}

	// Property accessors

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}