package com.cubepro.staff;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.cubepro.classes.ClassDetails;
import com.cubepro.util.DateUtils;

/**
 * StaffDetails generated by MyEclipse Persistence Tools
 */
public class StaffDetails implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 5042685059208338029L;

	// Fields

	private Integer staffId;

	//private Integer classDetails = new ClassDetails();

	private String firstName = "";

	private String staffNo = "";

	private Date dob;

	private String dobString;

	private Date doj;

	private String dojString;

	private String fatherName;

	private String motherName;

	private String guardianName;

	private String address1;

	private String address2;

	private String city;

	private String state;

	private String country;

	private String zipCode;

	private String phone;

	private String mobile;

	private Double salaryAmount;

	private String sex;

	private String qualification;

	private String designation;

	private String subjectHandled1;

	private String subjectHandled2;

	private String subjectHandled3;

	private String subjectHandled4;

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;

	private Integer statusId;

	private String secondName;
	private String dept;
	private String prevEmp;
	private String houseNo;
	private String houseName;
	private String street;
	private String pin;
	private String district;
	private String email;
	private String basicPay;
	private String hra;
	private String da;
	private String allow1;
	private String allow2;
	private String pfAmt;
	private String others;
	private String pfAcc;
	private String loanAmt;
	private String esiAmt;
	private String esiAcc;
	private String esiOthers;
	private String tdsAmt;
	private String tdsAcc;
	private String bankName;
	private String bankAcc;
	private String stamp;
	private String misc;
	private String co_optex;
	private String p_tax;
	private String staff_ex;
	private String guild;
	private String pli;
	private String rd;
	private String lic;
	private String diocesan;
	private String cma;
	private String t_a;
	private String ntc;
	private String spf_1;
	private String fa;
	private String pf_rec;
	private String pf_cont;
	private String hf;
	private String fbf;
	private String sa;
	private String o_a;
	private String m_a;
	private String p_p;
	private String d_p;
	private String type;
	private String isUsingTransport;
	private String isUsingHostel;
	private String isUsingLibrary;
	private String isUsingLab;
	private String photo;
	
	private Integer routeStopId ;
	private Integer roomId ;
	private Set timeTableDetailsesForReplacementStaffId = new HashSet(0);

	private Set timeTableDetailsesForStaffId = new HashSet(0);

	// Constructors

	/** default constructor */
	public StaffDetails() {
	}

	/** minimal constructor */
	public StaffDetails(Integer staffId, 
			String staffName, String staffNo, Date dob, Date doj,
			String fatherName, String address1, String city, String state,
			String country, String zipCode, Double salaryAmount, String sex,
			String qualification, String designation, String subjectHandled1,
			String subjectHandled2, String subjectHandled3,
			String subjectHandled4, Date createDate, Integer createUserId,
			Integer changeUserId, Integer statusId) {
		this.staffId = staffId;
		//this.classDetails = classDetails;
		this.staffNo = staffNo;
		this.dob = dob;
		this.doj = doj;
		this.fatherName = fatherName;
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipCode = zipCode;
		this.salaryAmount = salaryAmount;
		this.sex = sex;
		this.qualification = qualification;
		this.designation = designation;
		this.subjectHandled1 = subjectHandled1;
		this.subjectHandled2 = subjectHandled2;
		this.subjectHandled3 = subjectHandled3;
		this.subjectHandled4 = subjectHandled4;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeUserId = changeUserId;
		this.statusId = statusId;
	}

	/** full constructor */
	public StaffDetails(Integer staffId, 
			String staffName, String staffNo, Date dob, Date doj,
			String fatherName, String motherName, String guardianName,
			String address1, String address2, String city, String state,
			String country, String zipCode, String phone, String mobile,
			Double salaryAmount, String sex, String qualification,
			String designation, String subjectHandled1, String subjectHandled2,
			String subjectHandled3, String subjectHandled4, Date createDate,
			Integer createUserId, Date changeDate, Integer changeUserId,
			Integer statusId, Set timeTableDetailsesForReplacementStaffId,
			Set timeTableDetailsesForStaffId) {
		this.staffId = staffId;
		//this.classDetails = classDetails;
		this.staffNo = staffNo;
		this.dob = dob;
		this.doj = doj;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.guardianName = guardianName;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipCode = zipCode;
		this.phone = phone;
		this.mobile = mobile;
		this.salaryAmount = salaryAmount;
		this.sex = sex;
		this.qualification = qualification;
		this.designation = designation;
		this.subjectHandled1 = subjectHandled1;
		this.subjectHandled2 = subjectHandled2;
		this.subjectHandled3 = subjectHandled3;
		this.subjectHandled4 = subjectHandled4;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
		this.statusId = statusId;
		this.timeTableDetailsesForReplacementStaffId = timeTableDetailsesForReplacementStaffId;
		this.timeTableDetailsesForStaffId = timeTableDetailsesForStaffId;
	}

	// Property accessors

	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/*public ClassDetails getClassDetails() {
		return this.classDetails;
	}

	public void setClassDetails(ClassDetails classDetails) {
		this.classDetails = classDetails;
	}*/

	public String getStaffNo() {
		return this.staffNo;
	}

	public void setStaffNo(String staffNo) {
		this.staffNo = staffNo;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
		if (dob != null) {
			this.dobString = DateUtils.getDateAsString(dob);
		}
	}

	public Date getDoj() {
		return this.doj;
	}

	public void setDoj(Date doj) {
		this.doj = doj;
		if (doj != null) {
			this.dojString = DateUtils.getDateAsString(doj);
		}
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public String getGuardianName() {
		return this.guardianName;
	}

	public void setGuardianName(String guardianName) {
		this.guardianName = guardianName;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Double getSalaryAmount() {
		return this.salaryAmount;
	}

	public void setSalaryAmount(Double salaryAmount) {
		this.salaryAmount = salaryAmount;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getSubjectHandled1() {
		return this.subjectHandled1;
	}

	public void setSubjectHandled1(String subjectHandled1) {
		this.subjectHandled1 = subjectHandled1;
	}

	public String getSubjectHandled2() {
		return this.subjectHandled2;
	}

	public void setSubjectHandled2(String subjectHandled2) {
		this.subjectHandled2 = subjectHandled2;
	}

	public String getSubjectHandled3() {
		return this.subjectHandled3;
	}

	public void setSubjectHandled3(String subjectHandled3) {
		this.subjectHandled3 = subjectHandled3;
	}

	public String getSubjectHandled4() {
		return this.subjectHandled4;
	}

	public void setSubjectHandled4(String subjectHandled4) {
		this.subjectHandled4 = subjectHandled4;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public Set getTimeTableDetailsesForReplacementStaffId() {
		return this.timeTableDetailsesForReplacementStaffId;
	}

	public void setTimeTableDetailsesForReplacementStaffId(
			Set timeTableDetailsesForReplacementStaffId) {
		this.timeTableDetailsesForReplacementStaffId = timeTableDetailsesForReplacementStaffId;
	}

	public Set getTimeTableDetailsesForStaffId() {
		return this.timeTableDetailsesForStaffId;
	}

	public void setTimeTableDetailsesForStaffId(Set timeTableDetailsesForStaffId) {
		this.timeTableDetailsesForStaffId = timeTableDetailsesForStaffId;
	}

	public String getDobString() {
		return dobString;
	}

	public void setDobString(String dobString) {
		this.dobString = dobString;
		if (dobString != null && dobString.trim().length() > 0) {
			this.dob = DateUtils.getDate(dobString);
		}
	}

	public String getDojString() {
		return dojString;
	}

	public void setDojString(String dojString) {
		this.dojString = dojString;
		if (dojString != null && dojString.trim().length() > 0) {
			this.doj = DateUtils.getDate(dojString);
		}
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSecondName() {
		return secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getPrevEmp() {
		return prevEmp;
	}

	public void setPrevEmp(String prevEmp) {
		this.prevEmp = prevEmp;
	}

	public String getHouseNo() {
		return houseNo;
	}

	public void setHouseNo(String houseNo) {
		this.houseNo = houseNo;
	}

	public String getHouseName() {
		return houseName;
	}

	public void setHouseName(String houseName) {
		this.houseName = houseName;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getPin() {
		return pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getDistrict() {
		return district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBasicPay() {
		return basicPay;
	}

	public void setBasicPay(String basicPay) {
		this.basicPay = basicPay;
	}

	public String getHra() {
		return hra;
	}

	public void setHra(String hra) {
		this.hra = hra;
	}

	public String getDa() {
		return da;
	}

	public void setDa(String da) {
		this.da = da;
	}

	public String getAllow1() {
		return allow1;
	}

	public void setAllow1(String allow1) {
		this.allow1 = allow1;
	}

	public String getAllow2() {
		return allow2;
	}

	public void setAllow2(String allow2) {
		this.allow2 = allow2;
	}

	public String getPfAmt() {
		return pfAmt;
	}

	public void setPfAmt(String pfAmt) {
		this.pfAmt = pfAmt;
	}

	public String getOthers() {
		return others;
	}

	public void setOthers(String others) {
		this.others = others;
	}

	public String getPfAcc() {
		return pfAcc;
	}

	public void setPfAcc(String pfAcc) {
		this.pfAcc = pfAcc;
	}

	public String getLoanAmt() {
		return loanAmt;
	}

	public void setLoanAmt(String loanAmt) {
		this.loanAmt = loanAmt;
	}

	public String getEsiAmt() {
		return esiAmt;
	}

	public void setEsiAmt(String esiAmt) {
		this.esiAmt = esiAmt;
	}

	public String getEsiAcc() {
		return esiAcc;
	}

	public void setEsiAcc(String esiAcc) {
		this.esiAcc = esiAcc;
	}

	public String getEsiOthers() {
		return esiOthers;
	}

	public void setEsiOthers(String esiOthers) {
		this.esiOthers = esiOthers;
	}

	public String getTdsAmt() {
		return tdsAmt;
	}

	public void setTdsAmt(String tdsAmt) {
		this.tdsAmt = tdsAmt;
	}

	public String getTdsAcc() {
		return tdsAcc;
	}

	public void setTdsAcc(String tdsAcc) {
		this.tdsAcc = tdsAcc;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankAcc() {
		return bankAcc;
	}

	public void setBankAcc(String bankAcc) {
		this.bankAcc = bankAcc;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStamp() {
		return stamp;
	}

	public void setStamp(String stamp) {
		this.stamp = stamp;
	}

	public String getMisc() {
		return misc;
	}

	public void setMisc(String misc) {
		this.misc = misc;
	}

	public String getCo_optex() {
		return co_optex;
	}

	public void setCo_optex(String co_optex) {
		this.co_optex = co_optex;
	}

	public String getP_tax() {
		return p_tax;
	}

	public void setP_tax(String p_tax) {
		this.p_tax = p_tax;
	}

	public String getStaff_ex() {
		return staff_ex;
	}

	public void setStaff_ex(String staff_ex) {
		this.staff_ex = staff_ex;
	}

	public String getGuild() {
		return guild;
	}

	public void setGuild(String guild) {
		this.guild = guild;
	}

	public String getPli() {
		return pli;
	}

	public void setPli(String pli) {
		this.pli = pli;
	}

	public String getRd() {
		return rd;
	}

	public void setRd(String rd) {
		this.rd = rd;
	}

	public String getLic() {
		return lic;
	}

	public void setLic(String lic) {
		this.lic = lic;
	}

	public String getDiocesan() {
		return diocesan;
	}

	public void setDiocesan(String diocesan) {
		this.diocesan = diocesan;
	}

	public String getCma() {
		return cma;
	}

	public void setCma(String cma) {
		this.cma = cma;
	}

	public String getT_a() {
		return t_a;
	}

	public void setT_a(String t_a) {
		this.t_a = t_a;
	}

	public String getNtc() {
		return ntc;
	}

	public void setNtc(String ntc) {
		this.ntc = ntc;
	}

	public String getSpf_1() {
		return spf_1;
	}

	public void setSpf_1(String spf_1) {
		this.spf_1 = spf_1;
	}

	public String getFa() {
		return fa;
	}

	public void setFa(String fa) {
		this.fa = fa;
	}

	public String getPf_rec() {
		return pf_rec;
	}

	public void setPf_rec(String pf_rec) {
		this.pf_rec = pf_rec;
	}

	public String getPf_cont() {
		return pf_cont;
	}

	public void setPf_cont(String pf_cont) {
		this.pf_cont = pf_cont;
	}

	public String getHf() {
		return hf;
	}

	public void setHf(String hf) {
		this.hf = hf;
	}

	public String getFbf() {
		return fbf;
	}

	public void setFbf(String fbf) {
		this.fbf = fbf;
	}

	public String getSa() {
		return sa;
	}

	public void setSa(String sa) {
		this.sa = sa;
	}

	public String getO_a() {
		return o_a;
	}

	public void setO_a(String o_a) {
		this.o_a = o_a;
	}

	public String getM_a() {
		return m_a;
	}

	public void setM_a(String m_a) {
		this.m_a = m_a;
	}

	public String getP_p() {
		return p_p;
	}

	public void setP_p(String p_p) {
		this.p_p = p_p;
	}

	public String getD_p() {
		return d_p;
	}

	public void setD_p(String d_p) {
		this.d_p = d_p;
	}

	public Integer getRouteStopId() {
		return routeStopId;
	}

	public void setRouteStopId(Integer routeStopId) {
		this.routeStopId = routeStopId;
	}

	public Integer getRoomId() {
		return roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public String getIsUsingTransport() {
		return isUsingTransport;
	}

	public void setIsUsingTransport(String isUsingTransport) {
		this.isUsingTransport = isUsingTransport;
	}

	public String getIsUsingHostel() {
		return isUsingHostel;
	}

	public void setIsUsingHostel(String isUsingHostel) {
		this.isUsingHostel = isUsingHostel;
	}

	public String getIsUsingLibrary() {
		return isUsingLibrary;
	}

	public void setIsUsingLibrary(String isUsingLibrary) {
		this.isUsingLibrary = isUsingLibrary;
	}

	public String getIsUsingLab() {
		return isUsingLab;
	}

	public void setIsUsingLab(String isUsingLab) {
		this.isUsingLab = isUsingLab;
	}

	public String getPhoto() {
		if(photo==null)
			photo="#";
		return photo;
	}

	public void setPhoto(String photo) {
		if(photo==null)
			photo="#";
		this.photo = photo;
	}

}
