package com.cubepro.courses;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * CourseDetails generated by MyEclipse Persistence Tools
 */
public class CourseDetails implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 6777348295467835157L;

	private Integer courseId;

	private String courseName;

	private Double courseFee;

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;

	private Integer status;

	// Constructors

	/** default constructor */
	public CourseDetails() {
	}

	/** minimal constructor */
	public CourseDetails(Integer courseId, String courseName, Double courseFee,
			Date createDate, Integer createUserId, Integer changeUserId,
			Integer status) {
		this.courseId = courseId;
		this.courseName = courseName;
		this.courseFee = courseFee;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeUserId = changeUserId;
		this.status = status;
	}

	/** full constructor */
	public CourseDetails(Integer courseId, String courseName, Double courseFee,
			Date createDate, Integer createUserId, Date changeDate,
			Integer changeUserId, Integer status) {
		this.courseId = courseId;
		this.courseName = courseName;
		this.courseFee = courseFee;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
		this.status = status;
	}

	// Property accessors

	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Double getCourseFee() {
		return this.courseFee;
	}

	public void setCourseFee(Double courseFee) {
		this.courseFee = courseFee;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
