package com.cubepro.student;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.cubepro.classes.ClassDetails;
import com.cubepro.components.CubeProConstants;
import com.cubepro.util.DateUtils;

/**
 * StudentDetails generated by MyEclipse Persistence Tools
 */
public class StudentDetails implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 7526618073332754640L;

	private Integer studentId;

	private ClassDetails classDetails = new ClassDetails();

	private String studentName;
	
	private String lastName;
	
	private String medium;

	private String rollNo;

	private String dobString;
	
	private String dojString;

	private String fatherName;

	private String motherName;

	private String guardianName;

	private String address1;

	private String address2;

	private String city;
	
	private String govtRegNo;

	private String state;

	private String country;

	private String zipCode;

	private String phone;

	private String mobile;

	private String courseIds;

	private String gender;

	private Integer status;
	
	private String photo;
	
	private String caste;
	
	private String religion;
	
	private String nationality = CubeProConstants.NATIONALITY_INDIAN;
	
	private String bloodGroup;
	
	private String firstLanguage;
	
	private String secondLanguage;
	
	private String motherTongue;
	
	private String thirdLanguage;
	private String bookSerialNo;
	private String admissionNo;
	private String physicalStatus;
	private String scholarship;
	private String prevInst;
	private String prevInstReason;
	private String idenMark1;
	private String idenMark2;
	private String idenMark3;
	private String remarks;
	private String resHouseNo;
	private String resHouseName;
	private String category;
	private String subCategory;
	private String resHouseStreet;
	private String resHouseCity;
	private String resHousePinCode;
	private String resDistrict;
	private String resState;
	private String officeName;
	private String officeCompName;
	private String officeNo;
	private String officeStreet;
	private String officeCity;
	private String officeDist;
	private String officeState;
	private String officePinCode;
	private String landline1;
	private String mobile2;
	private String landline2;
	private String office2;
	private String altemail;
	private String email;
	private String emerName;
	private String emerMobileNo;
	private String emerLandlineNo;
	private String emerDoc;
	private String smsContName;
	private String smsRecNo;
	private String smsGateway;
	private String dobStringInWords;
	private String dojStringInWords;
	private String isUsingTransport; 
	private String isUsingScholar;
	private String scholar1;
	private String isUsingHostel;
	private String isUsingLibrary;
	private String isUsingLab;
	private Integer routeStopId ;
	private Integer roomId ;
	
	private String paidAmt;
	private String actualAmt;
	
	private String homeWorkDesc;
	
	private String homeWorkAssignedDate;
	private String homeWorkCompletionDate;

	private Set invoiceDetailses = new HashSet(0);

	private Set markDetailses = new HashSet(0);

	private List<ClassDetails> allClasses;

	private String total;
	private String percenTage;
	private String grade;
	private String pta;
	
	private String orderBy;
	// Constructors

	/** default constructor */
	public StudentDetails() {
	}

	/** minimal constructor */
	public StudentDetails(Integer studentId, ClassDetails classDetails,
			String studentName, String rollNo, Date dob, Date doj,
			String fatherName, String address1, String city, String state,
			String country, String zipCode, Integer status) {
		this.studentId = studentId;
		this.classDetails = classDetails;
		this.studentName = studentName;
		this.rollNo = rollNo;
		this.fatherName = fatherName;
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipCode = zipCode;
		this.status = status;
	}

	/** full constructor */
	public StudentDetails(Integer studentId, ClassDetails classDetails,
			String studentName, String rollNo, Date dob, Date doj,
			String fatherName, String motherName, String guardianName,
			String address1, String address2, String city, String state,
			String country, String zipCode, String phone, String mobile,
			String courseIds, String gender, Integer status,
			Set invoiceDetailses, Set markDetailses) {
		this.studentId = studentId;
		this.classDetails = classDetails;
		this.studentName = studentName;
		this.rollNo = rollNo;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.guardianName = guardianName;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipCode = zipCode;
		this.phone = phone;
		this.mobile = mobile;
		this.courseIds = courseIds;
		this.gender = gender;
		this.status = status;
		this.invoiceDetailses = invoiceDetailses;
		this.markDetailses = markDetailses;
	}

	// Property accessors

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public ClassDetails getClassDetails() {
		return this.classDetails;
	}

	public void setClassDetails(ClassDetails classDetails) {
		this.classDetails = classDetails;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public String getRollNo() {
		return this.rollNo;
	}

	public void setRollNo(String rollNo) {
		this.rollNo = rollNo;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public String getGuardianName() {
		return this.guardianName;
	}

	public void setGuardianName(String guardianName) {
		this.guardianName = guardianName;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getCourseIds() {
		return this.courseIds;
	}

	public void setCourseIds(String courseIds) {
		this.courseIds = courseIds;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Set getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}

	public Set getMarkDetailses() {
		return this.markDetailses;
	}

	public void setMarkDetailses(Set markDetailses) {
		this.markDetailses = markDetailses;
	}

	public List<ClassDetails> getAllClasses() {
		return allClasses;
	}

	public void setAllClasses(List<ClassDetails> allClasses) {
		this.allClasses = allClasses;
	}

	public String getDobString() {
		return dobString;
	}

	public void setDobString(String dobString) {
		this.dobString = dobString;
	}

	public String getDojString() {
		return dojString;
	}

	public void setDojString(String dojString) {
		this.dojString = dojString;
	}

	public String getPhoto() {
		if(photo==null)
			photo="#";
		return photo;
	}

	public void setPhoto(String photo) {
		if(photo==null)
			photo="#";
		this.photo = photo;
	}

	public String getCaste() {
		return caste;
	}

	public void setCaste(String caste) {
		this.caste = caste;
	}

	public String getReligion() {
		return religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getBloodGroup() {
		return bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public String getFirstLanguage() {
		return firstLanguage;
	}

	public void setFirstLanguage(String firstLanguage) {
		this.firstLanguage = firstLanguage;
	}

	public String getSecondLanguage() {
		return secondLanguage;
	}

	public void setSecondLanguage(String secondLanguage) {
		this.secondLanguage = secondLanguage;
	}

	public String getThirdLanguage() {
		return thirdLanguage;
	}

	public void setThirdLanguage(String thirdLanguage) {
		this.thirdLanguage = thirdLanguage;
	}

	public String getMotherTongue() {
		return motherTongue;
	}

	public void setMotherTongue(String motherTongue) {
		this.motherTongue = motherTongue;
	}

	public String getAdmissionNo() {
		return admissionNo;
	}

	public void setAdmissionNo(String admissionNo) {
		this.admissionNo = admissionNo;
	}

	public String getPhysicalStatus() {
		return physicalStatus;
	}

	public void setPhysicalStatus(String physicalStatus) {
		this.physicalStatus = physicalStatus;
	}

	public String getScholarship() {
		return scholarship;
	}

	public void setScholarship(String scholarship) {
		this.scholarship = scholarship;
	}

	public String getPrevInst() {
		return prevInst;
	}

	public void setPrevInst(String prevInst) {
		this.prevInst = prevInst;
	}

	public String getPrevInstReason() {
		return prevInstReason;
	}

	public void setPrevInstReason(String prevInstReason) {
		this.prevInstReason = prevInstReason;
	}

	public String getIdenMark1() {
		return idenMark1;
	}

	public void setIdenMark1(String idenMark1) {
		this.idenMark1 = idenMark1;
	}

	public String getIdenMark2() {
		return idenMark2;
	}

	public void setIdenMark2(String idenMark2) {
		this.idenMark2 = idenMark2;
	}

	public String getIdenMark3() {
		return idenMark3;
	}

	public void setIdenMark3(String idenMark3) {
		this.idenMark3 = idenMark3;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getResHouseNo() {
		return resHouseNo;
	}

	public void setResHouseNo(String resHouseNo) {
		this.resHouseNo = resHouseNo;
	}

	public String getResHouseName() {
		return resHouseName;
	}

	public void setResHouseName(String resHouseName) {
		this.resHouseName = resHouseName;
	}

	public String getResHouseStreet() {
		return resHouseStreet;
	}

	public void setResHouseStreet(String resHouseStreet) {
		this.resHouseStreet = resHouseStreet;
	}

	public String getResHouseCity() {
		return resHouseCity;
	}

	public void setResHouseCity(String resHouseCity) {
		this.resHouseCity = resHouseCity;
	}

	public String getResHousePinCode() {
		return resHousePinCode;
	}

	public void setResHousePinCode(String resHousePinCode) {
		this.resHousePinCode = resHousePinCode;
	}

	public String getOfficeName() {
		return officeName;
	}

	public void setOfficeName(String officeName) {
		this.officeName = officeName;
	}

	public String getOfficeCompName() {
		return officeCompName;
	}

	public void setOfficeCompName(String officeCompName) {
		this.officeCompName = officeCompName;
	}

	public String getOfficeNo() {
		return officeNo;
	}

	public void setOfficeNo(String officeNo) {
		this.officeNo = officeNo;
	}

	public String getOfficeStreet() {
		return officeStreet;
	}

	public void setOfficeStreet(String officeStreet) {
		this.officeStreet = officeStreet;
	}

	public String getOfficeCity() {
		return officeCity;
	}

	public void setOfficeCity(String officeCity) {
		this.officeCity = officeCity;
	}

	public String getOfficeDist() {
		return officeDist;
	}

	public void setOfficeDist(String officeDist) {
		this.officeDist = officeDist;
	}

	public String getOfficeState() {
		return officeState;
	}

	public void setOfficeState(String officeState) {
		this.officeState = officeState;
	}

	public String getOfficePinCode() {
		return officePinCode;
	}

	public void setOfficePinCode(String officePinCode) {
		this.officePinCode = officePinCode;
	}

	public String getMobile2() {
		return mobile2;
	}

	public void setMobile2(String mobile2) {
		this.mobile2 = mobile2;
	}


	public String getOffice2() {
		return office2;
	}

	public void setOffice2(String office2) {
		this.office2 = office2;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmerName() {
		return emerName;
	}

	public void setEmerName(String emerName) {
		this.emerName = emerName;
	}

	public String getEmerMobileNo() {
		return emerMobileNo;
	}

	public void setEmerMobileNo(String emerMobileNo) {
		this.emerMobileNo = emerMobileNo;
	}

	public String getEmerLandlineNo() {
		return emerLandlineNo;
	}

	public void setEmerLandlineNo(String emerLandlineNo) {
		this.emerLandlineNo = emerLandlineNo;
	}

	public String getEmerDoc() {
		return emerDoc;
	}

	public void setEmerDoc(String emerDoc) {
		this.emerDoc = emerDoc;
	}

	public String getSmsContName() {
		return smsContName;
	}

	public void setSmsContName(String smsContName) {
		this.smsContName = smsContName;
	}

	public String getSmsRecNo() {
		return smsRecNo;
	}

	public void setSmsRecNo(String smsRecNo) {
		this.smsRecNo = smsRecNo;
	}

	public String getSmsGateway() {
		return smsGateway;
	}

	public void setSmsGateway(String smsGateway) {
		this.smsGateway = smsGateway;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMedium() {
		return medium;
	}

	public void setMedium(String medium) {
		this.medium = medium;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getSubCategory() {
		return subCategory;
	}

	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	public String getResDistrict() {
		return resDistrict;
	}

	public void setResDistrict(String resDistrict) {
		this.resDistrict = resDistrict;
	}

	public String getResState() {
		return resState;
	}

	public void setResState(String resState) {
		this.resState = resState;
	}

	public String getDobStringInWords() {
		return DateUtils.getDateToWords(dobString);
	}

	public void setDobStringInWords(String dobStringInWords) {
		this.dobStringInWords = dobStringInWords;
	}

	public String getDojStringInWords() {
		return DateUtils.getDateToWords(dojString);
	}

	public void setDojStringInWords(String dojStringInWords) {
		this.dojStringInWords = dojStringInWords;
	}

	public String getAltemail() {
		return altemail;
	}

	public void setAltemail(String altemail) {
		this.altemail = altemail;
	}

	public String getLandline1() {
		return landline1;
	}

	public void setLandline1(String landline1) {
		this.landline1 = landline1;
	}

	public String getLandline2() {
		return landline2;
	}

	public void setLandline2(String landline2) {
		this.landline2 = landline2;
	}

	public String getBookSerialNo() {
		return bookSerialNo;
	}

	public void setBookSerialNo(String bookSerialNo) {
		this.bookSerialNo = bookSerialNo;
	}

	public String getIsUsingTransport() {
		return isUsingTransport;
	}

	public void setIsUsingTransport(String isUsingTransport) {
		this.isUsingTransport = isUsingTransport;
	}

	public String getIsUsingHostel() {
		return isUsingHostel;
	}

	public void setIsUsingHostel(String isUsingHostel) {
		this.isUsingHostel = isUsingHostel;
	}

	public String getIsUsingLibrary() {
		return isUsingLibrary;
	}

	public void setIsUsingLibrary(String isUsingLibrary) {
		this.isUsingLibrary = isUsingLibrary;
	}

	public String getIsUsingLab() {
		return isUsingLab;
	}

	public void setIsUsingLab(String isUsingLab) {
		this.isUsingLab = isUsingLab;
	}

	public Integer getRouteStopId() {
		return routeStopId;
	}

	public void setRouteStopId(Integer routeStopId) {
		this.routeStopId = routeStopId;
	}

	public Integer getRoomId() {
		return roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public String getTotal() {
		return total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public String getPercenTage() {
		return percenTage;
	}

	public void setPercenTage(String percenTage) {
		this.percenTage = percenTage;
	}

	public String getGrade() {
		return grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getIsUsingScholar() {
		return isUsingScholar;
	}

	public void setIsUsingScholar(String isUsingScholar) {
		this.isUsingScholar = isUsingScholar;
	}
    public String getScholar1() {
		return scholar1;
	}

	public void setScholar1(String scholar1) {
		this.scholar1 = scholar1;
	}

	public String getPaidAmt() {
		return paidAmt;
	}

	public void setPaidAmt(String paidAmt) {
		this.paidAmt = paidAmt;
	}

	public String getActualAmt() {
		return actualAmt;
	}

	public void setActualAmt(String actualAmt) {
		this.actualAmt = actualAmt;
	}

	public String getPta() {
		return pta;
	}

	public void setPta(String pta) {
		this.pta = pta;
	}

	public String getGovtRegNo() {
		return govtRegNo;
	}

	public void setGovtRegNo(String govtRegNo) {
		this.govtRegNo = govtRegNo;
	}

	public String getOrderBy() {
		return orderBy;
	}

	public void setOrderBy(String orderBy) {
		this.orderBy = orderBy;
	}

	public String getHomeWorkDesc() {
		return homeWorkDesc;
	}

	public void setHomeWorkDesc(String homeWorkDesc) {
		this.homeWorkDesc = homeWorkDesc;
	}

	public String getHomeWorkAssignedDate() {
		return homeWorkAssignedDate;
	}

	public void setHomeWorkAssignedDate(String homeWorkAssignedDate) {
		this.homeWorkAssignedDate = homeWorkAssignedDate;
	}

	public String getHomeWorkCompletionDate() {
		return homeWorkCompletionDate;
	}

	public void setHomeWorkCompletionDate(String homeWorkCompletionDate) {
		this.homeWorkCompletionDate = homeWorkCompletionDate;
	}

}
