package com.cubepro.transport;

// Generated by MyEclipse Persistence Tools

/**
 * ExamDetails generated by MyEclipse Persistence Tools
 */
public class Route implements java.io.Serializable {

	private Integer routeId = Integer.valueOf(0);

	private Vehicle vehicle = new Vehicle();

	private String routeName;

	private String startPoint;

	private String endPoint;

	private String totalKms;

	public Integer getRouteId() {
		return routeId;
	}

	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	public Vehicle getVehicle() {
		return vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public String getRouteName() {
		return routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	public String getStartPoint() {
		return startPoint;
	}

	public void setStartPoint(String startPoint) {
		this.startPoint = startPoint;
	}

	public String getEndPoint() {
		return endPoint;
	}

	public void setEndPoint(String endPoint) {
		this.endPoint = endPoint;
	}

	public String getTotalKms() {
		return totalKms;
	}

	public void setTotalKms(String totalKms) {
		this.totalKms = totalKms;
	}

}
