package com.cubepro.bank;


// Generated by MyEclipse Persistence Tools

/**
 * SubjectDetails generated by MyEclipse Persistence Tools
 */
public class BankDetails implements
		java.io.Serializable {
	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 5978438360474088634L;
	
	private Integer id;

	private Integer bankId;
	
	private String paymentType;
	
	private String dwDate;
	
	private String type;
	
	private String amt;
	
	private String remarks;
	
	private String bankName;

	public Integer getBankId() {
		return bankId;
	}

	public void setBankId(Integer bankId) {
		this.bankId = bankId;
	}

	public String getPaymentType() {
		return paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAmt() {
		return amt;
	}

	public void setAmt(String amt) {
		this.amt = amt;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDwDate() {
		return dwDate;
	}

	public void setDwDate(String dwDate) {
		this.dwDate = dwDate;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}	

	// Constructors
}
