package com.cubepro.staff.attendance;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.cubepro.staff.StaffDetails;

/**
 * StaffAttendanceDetails generated by MyEclipse Persistence Tools
 */
public class StaffAttendanceDetails 
		implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 3695308960897687466L;

	private Integer attendanceId= Integer.valueOf(0);;

	private String attendanceDate;
	
	private String attendanceDateString;

	private StaffDetails staffDetails;

	private String attendanceStatus;

	private String attendanceReason;

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;
	
	private String isApproved = "N";

	// Constructors

	/** default constructor */
	public StaffAttendanceDetails() {
	}

	/** minimal constructor */
	public StaffAttendanceDetails(Integer attendanceId,
			String attendanceDate, StaffDetails staffDetails, String attendanceStatus,
			String attendanceReason, Date createDate, Integer createUserId) {
		this.attendanceId = attendanceId;
		this.attendanceDate = attendanceDate;
		this.staffDetails = staffDetails;
		this.attendanceStatus = attendanceStatus;
		this.attendanceReason = attendanceReason;
		this.createDate = createDate;
		this.createUserId = createUserId;
	}

	/** full constructor */
	public StaffAttendanceDetails(Integer attendanceId,
			String attendanceDate, StaffDetails staffDetails, String attendanceStatus,
			String attendanceReason, Date createDate, Integer createUserId,
			Date changeDate, Integer changeUserId) {
		this.attendanceId = attendanceId;
		this.attendanceDate = attendanceDate;
		this.staffDetails = staffDetails;
		this.attendanceStatus = attendanceStatus;
		this.attendanceReason = attendanceReason;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.changeDate = changeDate;
		this.changeUserId = changeUserId;
	}

	// Property accessors

	public Integer getAttendanceId() {
		return this.attendanceId;
	}

	public void setAttendanceId(Integer attendanceId) {
		this.attendanceId = attendanceId;
	}

	public String getAttendanceDate() {
		return this.attendanceDate;
	}

	public void setAttendanceDate(String attendanceDate) {
		this.attendanceDate = attendanceDate;
		if (attendanceDate != null) {
			this.attendanceDateString = attendanceDate;
		}
	}

	public String getAttendanceStatus() {
		return this.attendanceStatus;
	}

	public void setAttendanceStatus(String attendanceStatus) {
		this.attendanceStatus = attendanceStatus;
	}

	public String getAttendanceReason() {
		return this.attendanceReason;
	}

	public void setAttendanceReason(String attendanceReason) {
		this.attendanceReason = attendanceReason;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public StaffDetails getStaffDetails() {
		return staffDetails;
	}

	public void setStaffDetails(StaffDetails staffDetails) {
		this.staffDetails = staffDetails;
	}

	public String getAttendanceDateString() {
		return attendanceDateString;
	}

	public void setAttendanceDateString(String attendanceDateString) {
		this.attendanceDateString = attendanceDateString;
		if (attendanceDateString != null && attendanceDateString.trim().length() > 0) {
			this.attendanceDate = attendanceDateString;
		}
	}

	public String getIsApproved() {
		return isApproved;
	}

	public void setIsApproved(String isApproved) {
		this.isApproved = isApproved;
	}


}
