package com.cubepro.mark;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.cubepro.classes.ClassDetails;
import com.cubepro.exam.ExamDetails;
import com.cubepro.student.StudentDetails;
import com.cubepro.subject.SubjectDetails;

/**
 * MarkDetails generated by MyEclipse Persistence Tools
 */
public class MarkDetails {

	// Fields


	private Integer markId = Integer.valueOf(0);

	private ClassDetails classDetails = new ClassDetails();;

	private ExamDetails examDetails = new ExamDetails();

	private StudentDetails studentDetails = new StudentDetails();

	private String markObtained;

	private String maxMarks;

	private Date createDate;

	private Integer createUserId;

	private Date changeDate;

	private Integer changeUserId;
	
	private SubjectDetails subjectDetails;

	// Constructors

	/** default constructor */
	public MarkDetails() {
	}

	/** minimal constructor */
	public MarkDetails(Integer markId, ClassDetails classDetails,
			ExamDetails examDetails, StudentDetails studentDetails,
			SubjectDetails subjectDetails, String maxMarks, Date createDate,
			Integer createUserId) {
		this.markId = markId;
		this.classDetails = classDetails;
		this.examDetails = examDetails;
		this.studentDetails = studentDetails;
		this.subjectDetails = subjectDetails;
		this.maxMarks = maxMarks;
		this.createDate = createDate;
		this.createUserId = createUserId;
	}

	// Property accessors

	public Integer getMarkId() {
		return this.markId;
	}

	public void setMarkId(Integer markId) {
		this.markId = markId;
	}

	public ClassDetails getClassDetails() {
		return this.classDetails;
	}

	public void setClassDetails(ClassDetails classDetails) {
		this.classDetails = classDetails;
	}

	public ExamDetails getExamDetails() {
		return this.examDetails;
	}

	public void setExamDetails(ExamDetails examDetails) {
		this.examDetails = examDetails;
	}

	public StudentDetails getStudentDetails() {
		return this.studentDetails;
	}

	public void setStudentDetails(StudentDetails studentDetails) {
		this.studentDetails = studentDetails;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	public Integer getChangeUserId() {
		return this.changeUserId;
	}

	public void setChangeUserId(Integer changeUserId) {
		this.changeUserId = changeUserId;
	}

	public SubjectDetails getSubjectDetails() {
		return subjectDetails;
	}

	public void setSubjectDetails(SubjectDetails subjectDetails) {
		this.subjectDetails = subjectDetails;
	}

	public String getMarkObtained() {
		return markObtained;
	}

	public void setMarkObtained(String markObtained) {
		this.markObtained = markObtained;
	}

	public String getMaxMarks() {
		return maxMarks;
	}

	public void setMaxMarks(String maxMarks) {
		this.maxMarks = maxMarks;
	}

}
